version: '3.8'
services:
    db:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_DATABASE: dbagenda
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: 123456
        ports:
            - "3306:3306"
        volumes: 
           - my-db:/var/lib/mysql/
volumes:
    my-db:
